version: "3.4"
services:
  api:
    image: adoptopenjdk:11-jre-hotspot
    working_dir: /webapps
    volumes: 
      - ./:/webapps
    ports:
      - 8080:8080
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
    # environment: 
    #    JAVA_OPTS: "$JAVA_OPTS -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n"
    command:
      - /bin/sh
      - -c
      - |
        java $JAVA_OPTS -jar *.jar --server.port=8080
#       java $JAVA_OPTS -jar *.jar --spring.profiles.active=test --server.port=8080        
